name: DePloY
on:
  push:
    paths:
      - "src/**/*"
      - "**.ts"
env:
  NODE_ENV: DePloY
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm i
      - name: Prepare to package
        run: npm run init
      - name: Package
        run: npm run pkg
  installer:
    needs: package
    runs-on: "ubuntu-latest"
    steps:
      - name: Download InstallBuilder
        run: |
          wget https://clients.bitrock.com/installbuilder/installbuilder-enterprise-19.10.0-linux-x64-installer.run
          chmod u+x installbuilder-enterprise-19.10.0-linux-x64-installer.run
      - name: Install InstallBuilder
        run: |
          ./installbuilder-enterprise-19.10.0-linux-x64-installer.run --installer-language en --prefix /root/installbuilder --mode unattended
          echo "${{ secrets.IBLICENSE }}" > ./installbuilder/license.xml
