name: DePloY
on:
  push:
    paths:
      - ".github/**/*"
      - "src/**/*"
      - "**.ts"
      - "package.json"
env:
  NODE_ENV: DePloY
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: |
          npm i
          npm i -g typescript rimraf
      - name: Prepare to package
        run: npm run init
      - name: Package
        run: |
          npm run pkg
          rimraf dist/app
          node util/zip dist ${{ matrix.os }}.zip --zip
      - name: Upload bundle
        env:
          SSHHOST: ${{ secrets.SSHHOST }}
          SSHUSERNAME: ${{ secrets.SSHUSERNAME }}
          SSHPASSWORD: ${{ secrets.SSHPASSWORD }}
        run: |
          tsc util/uploadFile util/zip
          node util/uploadFile ${{ matrix.os }}.zip /home/PreMiD/download/util/${{ matrix.os }}.zip
  createInstallers:
    runs-on: "ubuntu-latest"
    needs: package
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: |
          npm i
          npm i -g typescript
      - name: Download InstallBuilder
        run: |
          wget https://clients.bitrock.com/installbuilder/installbuilder-enterprise-19.10.0-linux-x64-installer.run
          chmod u+x installbuilder-enterprise-19.10.0-linux-x64-installer.run
      - name: Install InstallBuilder
        run: |
          ./installbuilder-enterprise-19.10.0-linux-x64-installer.run --installer-language en --prefix ./installbuilder --mode unattended
          echo "${{ secrets.IBLICENSE }}" > ./installbuilder/license.xml
      - name: Prepare Upgrade Installer
        run: |
          tsc util/prepare
          node util/prepare
      - name: Create Upgrade Installer (MacOS 64bit)
        run: |
          installbuilder/bin/builder build installer_assets/PreMiD-Upgrade.xml osx
      - name: Create Upgrade Installer (Windows)
        run: |
          installbuilder/bin/builder build installer_assets/PreMiD-Upgrade.xml windows
      - name: Upload files
        env:
          SSHHOST: ${{ secrets.SSHHOST }}
          SSHUSERNAME: ${{ secrets.SSHUSERNAME }}
          SSHPASSWORD: ${{ secrets.SSHPASSWORD }}
        run: |
          tsc util/uploadFile util/zip
          node util/uploadFile installer_assets/update.ini /home/PreMiD/download/util/update.ini
          node util/uploadFile dist/installer/upgrader.exe /home/PreMiD/download/upgrader.exe
          node util/zip dist/installer/upgrader.app dist/installer/upgrader.app.zip --zip
          node util/uploadFile dist/installer/upgrader.app.zip /home/PreMiD/download/util/upgrader.app.zip
      - name: Finalize build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/PreMiD/download/util
            unzip upgrader.app.zip
            tar -czvf upgrader.app.tgz upgrader.app
            mv upgrader.app.tgz ../
            rm -rf upgrader.app upgrader.app.zip
            unzip windows-latest.zip
            cp updater.exe windows-latest/PreMiD-win32-x64/updater.exe
            cp update.ini windows-latest/PreMiD-win32-x64/update.ini
            cp updater.exe windows-latest/PreMiD-win32-ia32/updater.exe
            cp update.ini windows-latest/PreMiD-win32-ia32/update.ini
            cd windows-latest/PreMiD-win32-x64/
            zip -r ../../PreMiD-win32-x64.zip .
            mv ../../PreMiD-win32-x64.zip /home/PreMiD/download/
            cd ../PreMiD-win32-ia32/
            zip -r ../../PreMiD-win32-x86.zip .
            mv ../../PreMiD-win32-x86.zip /home/PreMiD/download/
            cd ../..
            rm -rf windows-latest windows-latest.zip
            unzip macOS-latest.zip
            cp -r updater.app macOS-latest/PreMiD-darwin-x64/updater.app
            cp update.ini macOS-latest/PreMiD-darwin-x64/update.ini
            cd macOS-latest/PreMiD-darwin-x64/
            zip -r ../../PreMiD-darwin-x64.zip .
            mv ../../PreMiD-darwin-x64.zip /home/PreMiD/download/
            cd ../..
            rm -rf macOS-latest macOS-latest.zip
