name: DePloY
on: push
env: 
  NODE_ENV: DePloY
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Prepare build
        run: |
          npm run init
          npm run pkg
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/**
          draft: true
          name: DePloY
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        
