name: DePloY
on: push
env:
  NODE_ENV: DePloY
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm i
      - name: Prepare to package
        run: npm run init
      - name: Package
        run: npm run pkg
      - name: Upload to server
        env:
          SSH_HOST: ${{ secrets.SSHHOST }}
          SSH_USERNAME: ${{ secrets.SSHUSERNAME }}
          SSH_PASSWORD: ${{ secrets.SSHPASSWORD }}
        run: npm run deploy
  installer:
    needs: package
    runs-on: "ubuntu-latest"
    steps:
      - name: Prepare for installer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/PreMiD/builds
            unzip darwin.zip
            rm -r darwin.zip
            unzip win32.zip
            rm -r win32.zip
