name: DePloY
on: push
env: 
  NODE_ENV: DePloY
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Prepare build
        run: |
          npm run init
          npm run pkg
      - uses: SamKirkland/FTP-Deploy-Action@SFTP_Beta
        with:
          FTP_SERVER: ${{ secrets.HOST }}
          FTP_USERNAME: ${{ secrets.USERNAME }}
          FTP_PASSWORD: ${{ secrets.SSHKEY }}
          LOCAL_DIR: "dist"
          REMOTE_DIR: "/home/PreMiD/builds"
          ARGS: --transfer-all --parallel=5
        
