name: DePloY
on:
  push:
    paths:
      - ".github/**/*"
      - "src/**/*"
      - "**.ts"
      - "package.json"
env:
  NODE_ENV: DePloY
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm i
      - name: Prepare to package
        run: npm run init
      - name: Package
        run: |
          npm run pkg
          rm -r dist/app
      - name: Zip file
        run: zip ${{ matrix.os }}.zip dist/**/*
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}.zip
  installer:
    needs: package
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Download InstallBuilder
        run: |
          wget https://clients.bitrock.com/installbuilder/installbuilder-enterprise-19.10.0-linux-x64-installer.run
          chmod u+x installbuilder-enterprise-19.10.0-linux-x64-installer.run
      - name: Install InstallBuilder
        run: |
          ./installbuilder-enterprise-19.10.0-linux-x64-installer.run --installer-language en --prefix ./installbuilder --mode unattended
          echo "${{ secrets.IBLICENSE }}" > ./installbuilder/license.xml
      - uses: actions/download-artifact@master
        with:
          name: macOS-latest
      - name: Unzip File
        run: |
          unzip darwin.zip
          rm darwin.zip
      - name: Create Updater File
        run: |
          installbuilder/autoupdate/bin/customize.run build installer_assets/updater.xml osx
      - name: Create installer (MacOS 64bit)
        run: |
          npm i
          mkdir dist
          mv darwin/PreMiD-darwin-x64 dist/PreMiD-darwin-x64
          tsc util/prepare
          node util/prepare PreMiD-darwin-x64
          installbuilder/bin/builder build installer.xml osx
          zip PreMiD-darwin-x64.zip dist/installer/**/*
      - uses: actions/upload-artifact@master
        with:
          name: PreMiD-darwin-x64
          path: PreMiD-darwin-x64.zip
