name: DePloY
on: push
env: 
  NODE_ENV: DePloY
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Prepare build
        run: |
          npm run init
          npm run pkg
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORT }}
          port: 22
          source: "dist/**/*"
          target: "/home/PreMiD/builds/"
        
