name: DePloY
on: push
env: 
  NODE_ENV: DePloY
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Prepare build
        run: |
          npm run init
          npm run pkg
      - uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local: "dist/**/*"
          remote: "/home/PreMiD/builds/"
          concurrency: 10
        
