name: DePloY
on: push
env:
  NODE_ENV: DePloY
jobs:
  installbuilder:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get and install
        run: |
          wget https://installbuilder.bitrock.com/installbuilder-enterprise-19.9.0-linux-x64-installer.run
          chmod u+x installbuilder-enterprise-19.9.0-linux-x64-installer.run
          yes 'y' | ./installbuilder-enterprise-19.9.0-linux-x64-installer.run --installer-language en --prefix ./
          mv y installbuilder
          cd installbuilder
          echo "${{ secrets.IBLICENSE }}" >> licence.xml
          echo $PWD
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install Dependencies
        run: npm i
      - name: Prepare to package
        run: npm run init
      - name: Package
        run: |
          npm run pkg
          cd ..
          echo $PWD
